### PR TITLE
Fixed excluded fields

### PR DESCRIPTION
**Pull request by michalsvorc**
Input fields marked as excluded were persisted in web storage.

DONE:
- Fixed by filtering for excluded fields
- Updated README.md usage section for showcasing functionality
- Test cases for persisting all, included and excluded input fields

TODO:
- Fix `When testing, code that causes React state updates should be wrapped into act(...):` console warning while running tests

### CODE REVIEW

**Comment by quinnturner** [comment]
I haven't tested, but this hook (along with the code on master) might be vulnerable to prototype pollution. Consider reviewing https://codeburst.io/what-is-prototype-pollution-49482fc4b638

**Comment by michalsvorc** [comment]
Thanks for opening the [issue](https://github.com/tiaanduplessis/react-hook-form-persist/issues).

> I haven't tested, but this hook (along with the code on master) might be vulnerable to prototype pollution. Consider reviewing https://codeburst.io/what-is-prototype-pollution-49482fc4b638

**Comment by eddyhdzg** [comment]
🚀

**Comment by brenoos** [comment]
any chance to merge this? I'm using this package and we need to exclude some fields

**Comment by tiaanduplessis** [comment]
Thanks for the PR @michalsvorc. Sorry for the delay in merging

**Pull request merged**
